import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: "families",
      columns: [
        { name: "server_id", type: "string" },
        { name: "name", type: "string" },
        { name: "invite_code", type: "string" },
        { name: "ntfy_topic_prefix", type: "string" },
        { name: "created_by_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "members",
      columns: [
        { name: "server_id", type: "string" },
        { name: "name", type: "string" },
        { name: "email", type: "string" },
        { name: "role", type: "string" },
        { name: "family_id", type: "string", isIndexed: true },
        { name: "avatar", type: "string", isOptional: true },
        { name: "location_sharing_mode", type: "string", isOptional: true },
        { name: "location_sharing_until", type: "number", isOptional: true },
        { name: "last_lat", type: "number", isOptional: true },
        { name: "last_lng", type: "number", isOptional: true },
        { name: "last_location_at", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "lists",
      columns: [
        { name: "server_id", type: "string" },
        { name: "name", type: "string" },
        { name: "type", type: "string" },
        { name: "family_id", type: "string", isIndexed: true },
        { name: "assigned_to_id", type: "string", isOptional: true, isIndexed: true },
        { name: "status", type: "string" },
        { name: "sort_order", type: "number" },
        { name: "created_by_id", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "list_items",
      columns: [
        { name: "server_id", type: "string" },
        { name: "list_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "quantity", type: "string", isOptional: true },
        { name: "note", type: "string", isOptional: true },
        { name: "is_checked", type: "boolean" },
        { name: "checked_by_id", type: "string", isOptional: true },
        { name: "sort_order", type: "number" },
        { name: "created_by_id", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "location_history",
      columns: [
        { name: "server_id", type: "string" },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "lat", type: "number" },
        { name: "lng", type: "number" },
        { name: "accuracy", type: "number", isOptional: true },
        { name: "battery_level", type: "number", isOptional: true },
        { name: "timestamp", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "geofences",
      columns: [
        { name: "server_id", type: "string" },
        { name: "family_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "lat", type: "number" },
        { name: "lng", type: "number" },
        { name: "radius", type: "number" },
        { name: "notify_user_id", type: "string", isOptional: true, isIndexed: true },
        { name: "watch_user_id", type: "string", isOptional: true, isIndexed: true },
        { name: "trigger_on", type: "string", isOptional: true },
        { name: "is_enabled", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
  ],
});
