/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as DocsSelfHostingRouteImport } from './routes/docs/self-hosting'
import { Route as DocsReverseProxyRouteImport } from './routes/docs/reverse-proxy'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFlyIoRouteImport } from './routes/docs/fly-io'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as AuthServerUrlRouteImport } from './routes/auth/server-url'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthJoinFamilyRouteImport } from './routes/auth/join-family'
import { Route as AuthCreateFamilyRouteImport } from './routes/auth/create-family'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppLocationIndexRouteImport } from './routes/app/location/index'
import { Route as AppListsIndexRouteImport } from './routes/app/lists/index'
import { Route as DocsFeaturesLocationRouteImport } from './routes/docs/features/location'
import { Route as DocsFeaturesListsRouteImport } from './routes/docs/features/lists'
import { Route as DocsFeaturesGeofencesRouteImport } from './routes/docs/features/geofences'
import { Route as AppSettingsFamilyRouteImport } from './routes/app/settings/family'
import { Route as AppLocationSettingsRouteImport } from './routes/app/location/settings'
import { Route as AppLocationGeofencesRouteImport } from './routes/app/location/geofences'
import { Route as AppLocationCreateGeofenceRouteImport } from './routes/app/location/create-geofence'
import { Route as AppListsListIdRouteImport } from './routes/app/lists/$listId'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelfHostingRoute = DocsSelfHostingRouteImport.update({
  id: '/self-hosting',
  path: '/self-hosting',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReverseProxyRoute = DocsReverseProxyRouteImport.update({
  id: '/reverse-proxy',
  path: '/reverse-proxy',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFlyIoRoute = DocsFlyIoRouteImport.update({
  id: '/fly-io',
  path: '/fly-io',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AuthServerUrlRoute = AuthServerUrlRouteImport.update({
  id: '/auth/server-url',
  path: '/auth/server-url',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinFamilyRoute = AuthJoinFamilyRouteImport.update({
  id: '/auth/join-family',
  path: '/auth/join-family',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateFamilyRoute = AuthCreateFamilyRouteImport.update({
  id: '/auth/create-family',
  path: '/auth/create-family',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationIndexRoute = AppLocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsFeaturesLocationRoute = DocsFeaturesLocationRouteImport.update({
  id: '/features/location',
  path: '/features/location',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFeaturesListsRoute = DocsFeaturesListsRouteImport.update({
  id: '/features/lists',
  path: '/features/lists',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFeaturesGeofencesRoute = DocsFeaturesGeofencesRouteImport.update({
  id: '/features/geofences',
  path: '/features/geofences',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AppSettingsFamilyRoute = AppSettingsFamilyRouteImport.update({
  id: '/settings/family',
  path: '/settings/family',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationSettingsRoute = AppLocationSettingsRouteImport.update({
  id: '/location/settings',
  path: '/location/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationGeofencesRoute = AppLocationGeofencesRouteImport.update({
  id: '/location/geofences',
  path: '/location/geofences',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationCreateGeofenceRoute =
  AppLocationCreateGeofenceRouteImport.update({
    id: '/location/create-geofence',
    path: '/location/create-geofence',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppListsListIdRoute = AppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/features': typeof FeaturesRoute
  '/auth/create-family': typeof AuthCreateFamilyRoute
  '/auth/join-family': typeof AuthJoinFamilyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/server-url': typeof AuthServerUrlRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/fly-io': typeof DocsFlyIoRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reverse-proxy': typeof DocsReverseProxyRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/location/create-geofence': typeof AppLocationCreateGeofenceRoute
  '/app/location/geofences': typeof AppLocationGeofencesRoute
  '/app/location/settings': typeof AppLocationSettingsRoute
  '/app/settings/family': typeof AppSettingsFamilyRoute
  '/docs/features/geofences': typeof DocsFeaturesGeofencesRoute
  '/docs/features/lists': typeof DocsFeaturesListsRoute
  '/docs/features/location': typeof DocsFeaturesLocationRoute
  '/app/lists/': typeof AppListsIndexRoute
  '/app/location/': typeof AppLocationIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/auth/create-family': typeof AuthCreateFamilyRoute
  '/auth/join-family': typeof AuthJoinFamilyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/server-url': typeof AuthServerUrlRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/fly-io': typeof DocsFlyIoRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reverse-proxy': typeof DocsReverseProxyRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/location/create-geofence': typeof AppLocationCreateGeofenceRoute
  '/app/location/geofences': typeof AppLocationGeofencesRoute
  '/app/location/settings': typeof AppLocationSettingsRoute
  '/app/settings/family': typeof AppSettingsFamilyRoute
  '/docs/features/geofences': typeof DocsFeaturesGeofencesRoute
  '/docs/features/lists': typeof DocsFeaturesListsRoute
  '/docs/features/location': typeof DocsFeaturesLocationRoute
  '/app/lists': typeof AppListsIndexRoute
  '/app/location': typeof AppLocationIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/features': typeof FeaturesRoute
  '/auth/create-family': typeof AuthCreateFamilyRoute
  '/auth/join-family': typeof AuthJoinFamilyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/server-url': typeof AuthServerUrlRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/fly-io': typeof DocsFlyIoRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/reverse-proxy': typeof DocsReverseProxyRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/location/create-geofence': typeof AppLocationCreateGeofenceRoute
  '/app/location/geofences': typeof AppLocationGeofencesRoute
  '/app/location/settings': typeof AppLocationSettingsRoute
  '/app/settings/family': typeof AppSettingsFamilyRoute
  '/docs/features/geofences': typeof DocsFeaturesGeofencesRoute
  '/docs/features/lists': typeof DocsFeaturesListsRoute
  '/docs/features/location': typeof DocsFeaturesLocationRoute
  '/app/lists/': typeof AppListsIndexRoute
  '/app/location/': typeof AppLocationIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/features'
    | '/auth/create-family'
    | '/auth/join-family'
    | '/auth/login'
    | '/auth/server-url'
    | '/docs/faq'
    | '/docs/fly-io'
    | '/docs/getting-started'
    | '/docs/reverse-proxy'
    | '/docs/self-hosting'
    | '/docs/troubleshooting'
    | '/app/'
    | '/docs/'
    | '/app/lists/$listId'
    | '/app/location/create-geofence'
    | '/app/location/geofences'
    | '/app/location/settings'
    | '/app/settings/family'
    | '/docs/features/geofences'
    | '/docs/features/lists'
    | '/docs/features/location'
    | '/app/lists/'
    | '/app/location/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/auth/create-family'
    | '/auth/join-family'
    | '/auth/login'
    | '/auth/server-url'
    | '/docs/faq'
    | '/docs/fly-io'
    | '/docs/getting-started'
    | '/docs/reverse-proxy'
    | '/docs/self-hosting'
    | '/docs/troubleshooting'
    | '/app'
    | '/docs'
    | '/app/lists/$listId'
    | '/app/location/create-geofence'
    | '/app/location/geofences'
    | '/app/location/settings'
    | '/app/settings/family'
    | '/docs/features/geofences'
    | '/docs/features/lists'
    | '/docs/features/location'
    | '/app/lists'
    | '/app/location'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/features'
    | '/auth/create-family'
    | '/auth/join-family'
    | '/auth/login'
    | '/auth/server-url'
    | '/docs/faq'
    | '/docs/fly-io'
    | '/docs/getting-started'
    | '/docs/reverse-proxy'
    | '/docs/self-hosting'
    | '/docs/troubleshooting'
    | '/app/'
    | '/docs/'
    | '/app/lists/$listId'
    | '/app/location/create-geofence'
    | '/app/location/geofences'
    | '/app/location/settings'
    | '/app/settings/family'
    | '/docs/features/geofences'
    | '/docs/features/lists'
    | '/docs/features/location'
    | '/app/lists/'
    | '/app/location/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  AuthCreateFamilyRoute: typeof AuthCreateFamilyRoute
  AuthJoinFamilyRoute: typeof AuthJoinFamilyRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthServerUrlRoute: typeof AuthServerUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/self-hosting': {
      id: '/docs/self-hosting'
      path: '/self-hosting'
      fullPath: '/docs/self-hosting'
      preLoaderRoute: typeof DocsSelfHostingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reverse-proxy': {
      id: '/docs/reverse-proxy'
      path: '/reverse-proxy'
      fullPath: '/docs/reverse-proxy'
      preLoaderRoute: typeof DocsReverseProxyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/fly-io': {
      id: '/docs/fly-io'
      path: '/fly-io'
      fullPath: '/docs/fly-io'
      preLoaderRoute: typeof DocsFlyIoRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/auth/server-url': {
      id: '/auth/server-url'
      path: '/auth/server-url'
      fullPath: '/auth/server-url'
      preLoaderRoute: typeof AuthServerUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join-family': {
      id: '/auth/join-family'
      path: '/auth/join-family'
      fullPath: '/auth/join-family'
      preLoaderRoute: typeof AuthJoinFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-family': {
      id: '/auth/create-family'
      path: '/auth/create-family'
      fullPath: '/auth/create-family'
      preLoaderRoute: typeof AuthCreateFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/location/': {
      id: '/app/location/'
      path: '/location'
      fullPath: '/app/location/'
      preLoaderRoute: typeof AppLocationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lists/': {
      id: '/app/lists/'
      path: '/lists'
      fullPath: '/app/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/features/location': {
      id: '/docs/features/location'
      path: '/features/location'
      fullPath: '/docs/features/location'
      preLoaderRoute: typeof DocsFeaturesLocationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/features/lists': {
      id: '/docs/features/lists'
      path: '/features/lists'
      fullPath: '/docs/features/lists'
      preLoaderRoute: typeof DocsFeaturesListsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/features/geofences': {
      id: '/docs/features/geofences'
      path: '/features/geofences'
      fullPath: '/docs/features/geofences'
      preLoaderRoute: typeof DocsFeaturesGeofencesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/app/settings/family': {
      id: '/app/settings/family'
      path: '/settings/family'
      fullPath: '/app/settings/family'
      preLoaderRoute: typeof AppSettingsFamilyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/location/settings': {
      id: '/app/location/settings'
      path: '/location/settings'
      fullPath: '/app/location/settings'
      preLoaderRoute: typeof AppLocationSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/location/geofences': {
      id: '/app/location/geofences'
      path: '/location/geofences'
      fullPath: '/app/location/geofences'
      preLoaderRoute: typeof AppLocationGeofencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/location/create-geofence': {
      id: '/app/location/create-geofence'
      path: '/location/create-geofence'
      fullPath: '/app/location/create-geofence'
      preLoaderRoute: typeof AppLocationCreateGeofenceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lists/$listId': {
      id: '/app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/app/lists/$listId'
      preLoaderRoute: typeof AppListsListIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppLocationCreateGeofenceRoute: typeof AppLocationCreateGeofenceRoute
  AppLocationGeofencesRoute: typeof AppLocationGeofencesRoute
  AppLocationSettingsRoute: typeof AppLocationSettingsRoute
  AppSettingsFamilyRoute: typeof AppSettingsFamilyRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppLocationIndexRoute: typeof AppLocationIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppLocationCreateGeofenceRoute: AppLocationCreateGeofenceRoute,
  AppLocationGeofencesRoute: AppLocationGeofencesRoute,
  AppLocationSettingsRoute: AppLocationSettingsRoute,
  AppSettingsFamilyRoute: AppSettingsFamilyRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppLocationIndexRoute: AppLocationIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFlyIoRoute: typeof DocsFlyIoRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsReverseProxyRoute: typeof DocsReverseProxyRoute
  DocsSelfHostingRoute: typeof DocsSelfHostingRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsFeaturesGeofencesRoute: typeof DocsFeaturesGeofencesRoute
  DocsFeaturesListsRoute: typeof DocsFeaturesListsRoute
  DocsFeaturesLocationRoute: typeof DocsFeaturesLocationRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsFaqRoute: DocsFaqRoute,
  DocsFlyIoRoute: DocsFlyIoRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsReverseProxyRoute: DocsReverseProxyRoute,
  DocsSelfHostingRoute: DocsSelfHostingRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsFeaturesGeofencesRoute: DocsFeaturesGeofencesRoute,
  DocsFeaturesListsRoute: DocsFeaturesListsRoute,
  DocsFeaturesLocationRoute: DocsFeaturesLocationRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  AuthCreateFamilyRoute: AuthCreateFamilyRoute,
  AuthJoinFamilyRoute: AuthJoinFamilyRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthServerUrlRoute: AuthServerUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
